
-- 특정 기간 이후 STOCK_RECORDS 조회 
CREATE OR REPLACE PROCEDURE USP_GET_LIST_STOCK_RECORDS(
	PI_STOCK_CODE IN STOCK_RECORDS.STOCK_CODE%TYPE,
	PI_T_DATE IN STOCK_RECORDS.T_DATE%TYPE,
	PO_CURSOR OUT SYS_REFCURSOR)
IS
BEGIN
	OPEN PO_CURSOR FOR
		SELECT *
		FROM STOCK_RECORDS
		WHERE STOCK_CODE = PI_STOCK_CODE
			AND T_DATE > PI_T_DATE
		ORDER BY T_DATE;
END;
/

-- 회사명이나 회사코드로 Company 선택해서 조회
CREATE OR REPLACE PROCEDURE USP_GET_COMPANY(
	PI_KEYWORD IN VARCHAR,
	PO_CURSOR OUT SYS_REFCURSOR)
IS
BEGIN
	OPEN PO_CURSOR FOR
		SELECT *
		FROM COMPANY
		WHERE STOCK_CODE = PI_KEYWORD
			OR COMPANY = PI_KEYWORD;
END;
/

-- 회사명이나 회사코드를 검색해서 해당 키워드가 들어가는 Company List
CREATE OR REPLACE PROCEDURE USP_SEARCH_LIST_COMPANY(
	PI_KEYWORD IN VARCHAR,
	PO_CURSOR OUT SYS_REFCURSOR)
IS
BEGIN
	OPEN PO_CURSOR FOR
		SELECT *
		FROM COMPANY
		WHERE STOCK_CODE LIKE '%'||PI_KEYWORD||'%'
			OR COMPANY LIKE '%'||PI_KEYWORD||'%'
		ORDER BY COMPANY;
END;
/

-- 
